#Program name

OBJS = 5_div_Prog4_2.o

DEBUG = 1

ifdef DEBUG
DEBUGFLGS = -g

else
DEBUGFLGS =
endif

# The % is a wildcard.  For below, reads as for all .s files and create a .0 file with DEBUGFLGS output
%.o : %.s
	as $(DEBUGFLGS) $< -o $@
${PROG}: $(OBJS)
	ld -o 5_div_Prog4_2 $(OBJS)

#cleanup
clean: $(OBJS)
	rm *.o 5_div_Prog4_2
